apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgre-storage
          persistentVolumeClaim:
            claimName: database-persistent-vloume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgress-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgress
          env:
            - name: PGPASSWORD
              valueFrom:
                screateKeyRed:
                 name: pgpassword
                 key: PGPASSWORD
